title: Lampe „Panta Rhei“

date: "2012-07-15"

media: computergestützte Skulptur

material: LED-Lampe, Schriftschablone (Holz), TP-Link TL-WR703N Wifi-Router, Relais, Schaltkasten

content: >
  Lampe, die nur bei stabiler Internetverbindung leuchtet.

  *Lamp which only glows with an stable internet connection.*

  Prototyp: Insel Hydra, Griechenland, Mai 2012
  Ausstellung: Rundgang der Bauhaus-Uni Weimar, Juli 2012

colophon: >
  Enstanden im Projekt "Panta Rhei" bei
  Naomi T. Salmon & Norbert W. Hinterberger, Bauhaus-Universität Weimar.
