title: insert coin

date: 2009-11-01

material: Fotomontage

01.jpg:
  description: CAPTION

content: +++
insert coin/drehkreuz 

concept for intervention in public space
+++

colophon: +++
project: WECHSELSTROM (1) professor: Liz Bachhuber
+++