title: insert coin

date: 2009-11-01

material: Fotomontage

media:
  - source: btc/btc-vending-machine.jpg
    caption: exhibiton view at M18, Weimar

content: >
  insert coin/drehkreuz

  concept for intervention in public space


colophon: >
  project: WECHSELSTROM (1) professor: Liz Bachhuber
