title: Schwarzer Koffer

date: 2011-03-19

media: Replikat

size: 40 × 30 × 7 cm

material: 
  - Koffer
  - Umschlag mit 100.00 DM (Deutsche Mark)
  - Quittungsblock (unbenutzt)
  - Kugelschreiber

01.jpg:
  description: CAPTION

content: +++
> „Nicht der Staat bedroht Freiheit und Sicherheit, sondern die Rechtsbrecher. Wer was anderes sagt, ist verrückt.“ — *Dr. Wolfgang Schäuble, 2008*

> „1999 hatte Dr. Schäuble im Bundestag erklärt, Karlheinz Schreiber im Rahmen eines Gesprächsabends 1994 in Bonn kennen gelernt zu haben. Dort habe er sich ihm als Unternehmer vorgestellt. Den Erhalt einer Barspende Schreibers hatte Dr. Schäuble allerdings unerwähnt gelassen: „Auf der damaligen Veranstaltung bin ich Herrn Schreiber begegnet. Das war es.“ Auf die Nachfrage, ob dies mit oder ohne Koffer geschehen sei – wobei der Begriff „Koffer“ als Synonym für die Übergabe von Bargeld zu verstehen ist – hatte Dr. Schäuble geantwortet: „Ohne Koffer, das heißt: Ich habe vielleicht einen Aktenkoffer dabei gehabt. Ich weiß es nicht mehr genau.“ Im Dezember 1999 wurde Dr. Schäuble zu einer etwaigen Barspende Schreibers befragt. Dort erklärte er erstmals, im September 1994 von Schreiber eine Spende in Höhe von 100.000 DM erhalten zu haben.“ — *14. Dt. Bundestag, Drucks. 14/9300: Bericht d. Untersuchungsausschusses „Parteispenden und Waffenhandel“, S.165 (gekürzt)*

Ausstellung: <http://geldoderleben.tk>
+++

colophon: +++
Enstanden im Projekt "Geld oder Leben" im Wintersemester 2010/2011 bei Naomi-Tereza Salmon & Norbert W. Hinterberger, Bauhaus-Universität Weimar.
+++