title: „Auch ich in Arkadien!“

date: 2012-03-10

media: netart

material: WordPress, „Italienische Reise — Band 1“ von Johann Wolfgang von Goethe

content: +++
Echzeit-Blog-Version des Briefromans „Italienische Reise — Band 1“ von Johann Wolfgang von Goethe. 

Die 232 Briefe wurden jeweils 225 Jahre nach ihrer usprünglichen Erstellung veröffentlicht, die Reise dauerte vom 3.9.2011 bis zum 6.6.2012.

Webseite: <http://italienischereise.ars.is>
+++

auch_ich_in_arkadien_italienischereise.ars_.is_mfa.png:
  description: Screenshot der Webseite

